version: '3.8'

services:
  # PostgreSQL Database (Production)
  blacklist-postgres-prod:
    image: registry.jclee.me/blacklist-postgres:latest
    container_name: blacklist-postgres-prod
    restart: unless-stopped
    environment:
      - POSTGRES_DB=blacklist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - blacklist-prod-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "/usr/local/bin/pg_health_check.sh"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  # Redis Cache (Production)
  blacklist-redis-prod:
    image: registry.jclee.me/blacklist-redis:latest
    container_name: blacklist-redis-prod
    restart: unless-stopped
    volumes:
      - redis_prod_data:/data
    networks:
      - blacklist-prod-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'

  # Main Application (Production with Gunicorn)
  blacklist-app-prod:
    image: registry.jclee.me/blacklist-app:latest
    container_name: blacklist-app-prod
    restart: unless-stopped
    depends_on:
      blacklist-postgres-prod:
        condition: service_healthy
      blacklist-redis-prod:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=blacklist-postgres-prod
      - POSTGRES_PORT=5432
      - POSTGRES_DB=blacklist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - REDIS_HOST=blacklist-redis-prod
      - REDIS_PORT=6379
      - FLASK_ENV=production
      - PORT=2542
      - WORKERS=${GUNICORN_WORKERS:-4}
    volumes:
      - app_prod_logs:/app/logs
      - app_prod_data:/app/data
    networks:
      - blacklist-prod-network
    ports:
      - "2542:2542"
    healthcheck:
      test: ["CMD", "python", "/app/health_check_prod.py"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    labels:
      - "com.blacklist.service=app"
      - "com.blacklist.version=production"
      - "com.blacklist.environment=prod"


volumes:
  postgres_prod_data:
    driver: local
  redis_prod_data:
    driver: local
  app_prod_logs:
    driver: local
  app_prod_data:
    driver: local

networks:
  blacklist-prod-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16