version: '3.8'

services:
  postgres:
    image: registry.jclee.me/blacklist-postgres:latest
    container_name: blacklist-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=blacklist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blacklist-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blacklist"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  redis:
    image: registry.jclee.me/blacklist-redis:latest
    container_name: blacklist-redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Seoul
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,KEYS,PEXPIRE,DEL,EVAL,SHUTDOWN
      - REDIS_REPLICATION_DISABLED=yes
    volumes:
      - redis_data:/data
      - redis_run:/var/run/redis
      - ./redis-silent.conf:/usr/local/etc/redis/redis.conf
    tmpfs:
      - /tmp
    networks:
      - blacklist-network
    ports:
      - "32544:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  app:
    build: .
    image: registry.jclee.me/blacklist-app:latest
    container_name: blacklist-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=blacklist-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=blacklist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=blacklist-redis
      - REDIS_PORT=6379
      - FLASK_ENV=production
      - PORT=2542
      - TZ=Asia/Seoul
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
      - GUNICORN_WORKERS=4
      - GUNICORN_MAX_REQUESTS=1000
    volumes:
      - app_logs:/app/logs
      - app_data:/app/data
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    networks:
      - blacklist-network
    ports:
      - "2542:2542"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:2542/health || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  postgres_data:
  redis_data:
  redis_run:
  app_logs:
  app_data:

networks:
  blacklist-network:
    external: true